### ISSUE TITLE
Add a way to get the gyro heading in +-1800

### ISSUE THREAD

**Issue by Octogonapus** [OkapiLib/OkapiLib#224]
A few people have expressed interest in a way to get the gyro angle from `[-1800, 1800]`. This is a reasonable request we should support.

If the gyro heading is `[0, 3600]` then this should be implemented as:
```
(x - 1800) % 3600 - 1800
```
Which is equivalent to, but faster than:
```
remapRange((x - 1800) % 3600, 0, 3600, -1800, 1800)
```

**Comment by PixelDust22** [comment]
If I remember correctly, because the VEX gyroscope uses analog IO, its value is going to have a sudden jump from 3600 to 0 when the robot makes a whole rotation. In some circumstances it would be helpful to get the value in [-∞, +∞], so that when the robot rotates 361 degrees the return value would be 3610 instead of 10, when the robot makes 2 whole rotations the return value would be 7200 instead of 0, etc.
I'm not sure if this was already implemented in PROS core or OkapiLib?

**Comment by Octogonapus** [comment]
My original assumption was wrong. The gyro value is `[-3600, +3600]`.
