### ISSUE TITLE
Motion Profiling

### ISSUE THREAD

**Issue by Octogonapus** [OkapiLib/OkapiLib#60]
@j-mmc Can create more specific issues for what he is working on.

**Comment by j-mmc** [comment]
We need an API for 1D/2D motion profiling in order to program complex motion control for one or two dimensional movement problems. A `MotionPlanner` can be configured to model different motion applications for deferentially driven robot chassis or arms, including following complex motion (bezier curves, splines, arcs of constant radius) and produce a timetable of velocity/position set points that can be passed to a motion controller, or directly fed into the V5 motor.

_Working on 1D motion profiling as an initial release_

**Comment by Octogonapus** [comment]
I agree with planning 1D for the June 1st release. When you have more ideas for how you want to architect 2D profiling, why don't you open an issue for that?

Also as an aside, this is a nit, but I tend to label commits associated with an issue like `Issue #0: blah` (note the colon).

**Comment by Octogonapus** [comment]
This has gone on for too long with no progress. I am closing it. We will do 1D motion profiling with Pathfinder.
